server:
  port: 10088

logging:
  level:
    root: INFO
    com:
      ms: ${LOG_LEVEL_MS:TRACE}

spring:
  main:
    allow-bean-definition-overriding: true
  zipkin:
    enabled: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      idleTimeout: 300000
      maximumPoolSize: 20
      minimumIdle: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: library
        format_sql: true
  flyway:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    user: postgres
    password: password
    schemas: library
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true